server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: productos-service
              uri: lb://producto
              predicates:
                - Path=/api/v2/productos/**, /api/v2/categorias/**, /api/v2/marcas/**, /api/v2/colores/**, /api/v2/tipoProductos/**, /producto/api-docs/**

            - id: locales-service
              uri: lb://local
              predicates:
                - Path=/api/v2/locales/**, /api/v2/comunas/**, /api/v2/regiones/**, /api/v2/colaboradores/**, /api/v2/cargos/**, /Local/api-docs/**

            - id: ventas-service
              uri: lb://ventas
              predicates:
                - Path=/api/v2/ventas/**, /api/v2/pagos/**, /api/v2/tarjetas/**, /api/v2/transferencias/**, /ventas/api-docs/**
            
            - id: clientes-service
              uri: lb://cliente
              predicates:
                - Path=/api/v2/clientes/**, /cliente/api-docs/**

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - name: Microservicio Ventas
        url: /ventas/api-docs
      - name: Microservicio Locales
        url: /Local/api-docs
      - name: Microservicio Productos
        url: /producto/api-docs
      - name: Microservicio Clientes
        url: /cliente/api-docs
  api-docs:
    enabled: true