server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: productos-service
              uri: lb://producto
              predicates:
                - Path=/api/v1/productos/**, /api/v1/categorias/**, /api/v1/marcas/**, /producto/api-docs/**

            - id: locales-service
              uri: lb://local
              predicates:
                - Path=/api/v1/locales/**, /api/v1/comunas/**, /api/v1/regiones/**, /Local/api-docs/**

            - id: ventas-service
              uri: lb://ventas
              predicates:
                - Path=/api/v1/ventas/**, /api/v1/pagos/**, /ventas/api-docs/**
            
            - id: clientes-service
              uri: lb://cliente
              predicates:
                - Path=/api/v1/clientes/**, /cliente/api-docs/**

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - name: Microservicio Ventas
        url: /ventas/api-docs
      - name: Microservicio Locales
        url: /Local/api-docs
      - name: Microservicio Productos
        url: /producto/api-docs
      - name: Microservicio Clientes
        url: /cliente/api-docs
  api-docs:
    enabled: true